services:
  dns:
    container_name: dns
    hostname: dns
    build:
      context: ./requirements/dns
      dockerfile: Dockerfile
      tags:
        - dns
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  ftp:
    container_name: ftp
    hostname: ftp
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
      tags:
        - ftp
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASSWORD=${FTP_PASSWORD}
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      tags:
        - mariadb
      args:
        - DB_GROUP=${DB_GROUP}
        - DB_USER=${DB_USER}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - WP_USER_NICKNAME=${WP_USER_NICKNAME}
        - WP_USER_LOGIN=${WP_USER_LOGIN}
        - WP_USER_PASS=${WP_USER_PASS}
        - WP_USER_EMAIL=${WP_USER_EMAIL}
        - WP_USER_DISPLAY_NAME=${WP_USER_DISPLAY_NAME}
        - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - wp_db
      - adminer_db
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
      tags:
        - adminer
      args:
        - PHP_VERSION=${PHP_VERSION}
        - ADMINER_VERSION=${ADMINER_VERSION}
    networks:
      - proxy_adminer
      - adminer_db
    volumes:
      - adminer_data:/var/www/adminer
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      tags:
        - nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wp_data:/var/www/html:ro
      - adminer_data:/var/www/adminer:ro
      - ./requirements/nginx/files/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_adminer
      - proxy_wp
      - proxy_react
    depends_on:
      - wordpress
      - adminer
      - react
    restart: unless-stopped

  react:
    container_name: react
    hostname: react
    build:
      context: ./requirements/react
      dockerfile: Dockerfile
      tags:
        - react
    networks:
      - proxy_react
    restart: unless-stopped

  redis:
    container_name: redis
    hostname: redis
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
      tags:
        - redis
    networks:
      - wp_redis
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      tags:
        - wordpress
      args:
        - PHP_VERSION=${PHP_VERSION}
        - WP_VERSION=${WP_VERSION}
        - REDIS_CACHE_PLUGIN_VERSION=${REDIS_CACHE_PLUGIN_VERSION}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - proxy_wp
      - wp_db
      - wp_redis
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    environment:
      - WP_AUTH_KEY=${WP_AUTH_KEY}
      - WP_SECURE_AUTH_KEY=${WP_SECURE_AUTH_KEY}
      - WP_LOGGED_IN_KEY=${WP_LOGGED_IN_KEY}
      - WP_NONCE_KEY=${WP_NONCE_KEY}
      - WP_AUTH_SALT=${WP_AUTH_SALT}
      - WP_SECURE_AUTH_SALT=${WP_SECURE_AUTH_SALT}
      - WP_LOGGED_IN_SALT=${WP_LOGGED_IN_SALT}
      - WP_NONCE_SALT=${WP_NONCE_SALT}
    restart: unless-stopped

networks:
  proxy_wp:
  proxy_adminer:
  proxy_react:
  wp_db:
  adminer_db:
  wp_redis:

volumes:
  mariadb_data:
  adminer_data:
  wp_data:
