services:
  dns:
    container_name: dns
    hostname: dns
    build:
      context: ./requirements/dns
      dockerfile: Dockerfile
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN

  # dotnet:
  #   TODO: 適切な名前に変更する
  #   container_name: mariadb
  #   build:
  #     context: ./requirements/dotnet
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - dotnet_data:/app

  ftp:
    container_name: ftp
    hostname: ftp
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wp_data:/var/www/html

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - db_network
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    networks:
      - db_network
      - proxy_network
    volumes:
      - adminer_data:/var/www/adminer
    depends_on:
      - mariadb
    environment:
      - ADMINER_DEFAULT_DB_HOST=mariadb
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_DEFAULT_DB_NAME=wp

  proxy:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html:ro
      - adminer_data:/var/www/adminer:ro
    #   - ./requirements/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_network
    depends_on:
      - wordpress
      - adminer

  redis:
    container_name: redix
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    networks:
      - redis_network

  wordpress:
    container_name: wordpress_php_fpm
    hostname: wordpress-php-fpm
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - db_network
      - proxy_network
      - redis_network
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
      - redis

networks:
  proxy_network:
  db_network:
  redis_network:

volumes:
  mariadb_data:
  adminer_data:
  wp_data:
  dotnet_data:
