CREATE DATABASE __MYSQL_DATABASE__;

CREATE USER '__MYSQL_USER__' IDENTIFIED BY '__MYSQL_PASSWORD__';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON `__MYSQL_DATABASE__`.* TO '__MYSQL_USER__'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS test;
